version: '3'
services:
  server_api:
    image: node:stretch
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    volumes:
      - ../redis_data:/data
  awscli:
    image: amazon/aws-cli
    env_file: .env
    volumes:
      - .:/opt/app
      - ~/.aws:/root/.aws
    working_dir: /opt/app
